--
-- PostgreSQL database dump
--

\restrict SG9ktwNtAFuDzqSmu86KSBfdMm84KhU5cGG18czCpb6U47MPZCFILCYxw1faOKE

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-06-04 09:20:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 18121)
-- Name: AdditionalServices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AdditionalServices" (
    "Id" integer NOT NULL,
    "Service" text NOT NULL,
    "Cost" numeric NOT NULL,
    "Description" text
);


--
-- TOC entry 219 (class 1259 OID 18120)
-- Name: AdditionalServices_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AdditionalServices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AdditionalServices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 18207)
-- Name: BookingAdditionalService; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BookingAdditionalService" (
    "BookingId" integer NOT NULL,
    "AdditionalServiceId" integer NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 18211)
-- Name: Bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Bookings" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "RoomId" integer NOT NULL,
    "StartDate" timestamp without time zone CONSTRAINT "Bookings_StartDate_not_null1" NOT NULL,
    "Duration" integer CONSTRAINT "Bookings_Duration_not_null1" NOT NULL,
    "StatusId" integer NOT NULL,
    "CreationDate" date CONSTRAINT "Bookings_CreationDate_not_null1" NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 18210)
-- Name: Bookings_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Bookings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Bookings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 18195)
-- Name: Equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Equipment" (
    "Id" integer NOT NULL,
    "Equipment" text NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 18194)
-- Name: Equipment_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Equipment" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Equipment_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 18132)
-- Name: Role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Role" (
    "Id" integer NOT NULL,
    "Role" text NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 18131)
-- Name: Role_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Role" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Role_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 18204)
-- Name: RoomEquipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RoomEquipment" (
    "RoomId" integer NOT NULL,
    "EquipmentId" integer NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 18155)
-- Name: RoomType; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RoomType" (
    "Id" integer NOT NULL,
    "Type" text NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 18154)
-- Name: RoomType_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."RoomType" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RoomType_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 18165)
-- Name: Rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Rooms" (
    "Id" integer NOT NULL,
    "RoomTypeId" integer NOT NULL,
    "Capacity" integer NOT NULL,
    "Cost" numeric NOT NULL,
    "MinTime" integer NOT NULL,
    "Discount" numeric NOT NULL,
    "Description" text,
    "Rating" numeric NOT NULL,
    "Photo" text,
    "RoomName" text NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 18164)
-- Name: Rooms_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Rooms" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Rooms_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 18179)
-- Name: Status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Status" (
    "Id" integer NOT NULL,
    "Status" text NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 18178)
-- Name: Status_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Status" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Status_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 18142)
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Number" text NOT NULL,
    "Password" text NOT NULL,
    "RoleId" integer NOT NULL,
    "IsNotofication" boolean NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 18141)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5046 (class 0 OID 18121)
-- Dependencies: 220
-- Data for Name: AdditionalServices; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."AdditionalServices" VALUES (2, 'Кофе-брейк', 300.00, 'Кофе, чай, печенье на человека');
INSERT INTO public."AdditionalServices" VALUES (3, 'Флипчарт', 400.00, 'Маркерная доска с комплектом маркеров');
INSERT INTO public."AdditionalServices" VALUES (4, 'Проектор дополнительный', 600.00, 'Переносной проектор');
INSERT INTO public."AdditionalServices" VALUES (1, 'Ноутбук', 500.00, 'Ноутбук с установленным ПО');


--
-- TOC entry 5060 (class 0 OID 18207)
-- Dependencies: 234
-- Data for Name: BookingAdditionalService; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."BookingAdditionalService" VALUES (2, 2);
INSERT INTO public."BookingAdditionalService" VALUES (3, 1);
INSERT INTO public."BookingAdditionalService" VALUES (2, 1);
INSERT INTO public."BookingAdditionalService" VALUES (8, 2);
INSERT INTO public."BookingAdditionalService" VALUES (8, 1);
INSERT INTO public."BookingAdditionalService" VALUES (8, 3);
INSERT INTO public."BookingAdditionalService" VALUES (9, 3);


--
-- TOC entry 5062 (class 0 OID 18211)
-- Dependencies: 236
-- Data for Name: Bookings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Bookings" VALUES (4, 6, 3, '2025-04-18 09:00:00', 8, 3, '2025-04-03');
INSERT INTO public."Bookings" VALUES (3, 5, 4, '2025-04-20 11:00:00', 4, 1, '2025-04-05');
INSERT INTO public."Bookings" VALUES (2, 6, 2, '2025-04-16 14:00:00', 3, 1, '2025-04-02');
INSERT INTO public."Bookings" VALUES (8, 4, 18, '2026-05-23 19:06:50', 10, 1, '2026-05-03');
INSERT INTO public."Bookings" VALUES (9, 5, 16, '2026-05-03 19:34:08', 5, 3, '2026-05-03');


--
-- TOC entry 5058 (class 0 OID 18195)
-- Dependencies: 232
-- Data for Name: Equipment; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Equipment" VALUES (1, 'Wi-Fi');
INSERT INTO public."Equipment" VALUES (2, 'проектор');
INSERT INTO public."Equipment" VALUES (3, 'кулер');
INSERT INTO public."Equipment" VALUES (4, 'кондиционер');
INSERT INTO public."Equipment" VALUES (5, 'маркерная доска');
INSERT INTO public."Equipment" VALUES (6, 'розетки');
INSERT INTO public."Equipment" VALUES (7, 'акустика');
INSERT INTO public."Equipment" VALUES (8, 'флипчарт');
INSERT INTO public."Equipment" VALUES (9, 'микрофоны');


--
-- TOC entry 5048 (class 0 OID 18132)
-- Dependencies: 222
-- Data for Name: Role; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Role" VALUES (1, 'Администратор');
INSERT INTO public."Role" VALUES (2, 'Оператор');
INSERT INTO public."Role" VALUES (3, 'Клиент');


--
-- TOC entry 5059 (class 0 OID 18204)
-- Dependencies: 233
-- Data for Name: RoomEquipment; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."RoomEquipment" VALUES (6, 1);
INSERT INTO public."RoomEquipment" VALUES (5, 1);
INSERT INTO public."RoomEquipment" VALUES (4, 1);
INSERT INTO public."RoomEquipment" VALUES (3, 1);
INSERT INTO public."RoomEquipment" VALUES (2, 1);
INSERT INTO public."RoomEquipment" VALUES (5, 2);
INSERT INTO public."RoomEquipment" VALUES (4, 2);
INSERT INTO public."RoomEquipment" VALUES (2, 2);
INSERT INTO public."RoomEquipment" VALUES (3, 3);
INSERT INTO public."RoomEquipment" VALUES (6, 4);
INSERT INTO public."RoomEquipment" VALUES (4, 4);
INSERT INTO public."RoomEquipment" VALUES (3, 6);
INSERT INTO public."RoomEquipment" VALUES (5, 7);
INSERT INTO public."RoomEquipment" VALUES (4, 8);
INSERT INTO public."RoomEquipment" VALUES (5, 9);
INSERT INTO public."RoomEquipment" VALUES (17, 1);
INSERT INTO public."RoomEquipment" VALUES (17, 2);
INSERT INTO public."RoomEquipment" VALUES (17, 3);
INSERT INTO public."RoomEquipment" VALUES (17, 4);
INSERT INTO public."RoomEquipment" VALUES (17, 5);
INSERT INTO public."RoomEquipment" VALUES (17, 6);
INSERT INTO public."RoomEquipment" VALUES (17, 7);
INSERT INTO public."RoomEquipment" VALUES (17, 8);
INSERT INTO public."RoomEquipment" VALUES (17, 9);
INSERT INTO public."RoomEquipment" VALUES (18, 1);
INSERT INTO public."RoomEquipment" VALUES (18, 8);
INSERT INTO public."RoomEquipment" VALUES (2, 4);
INSERT INTO public."RoomEquipment" VALUES (23, 6);
INSERT INTO public."RoomEquipment" VALUES (23, 9);


--
-- TOC entry 5052 (class 0 OID 18155)
-- Dependencies: 226
-- Data for Name: RoomType; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."RoomType" VALUES (1, 'Переговорная');
INSERT INTO public."RoomType" VALUES (2, 'Офис');
INSERT INTO public."RoomType" VALUES (3, 'Рабочее место');
INSERT INTO public."RoomType" VALUES (4, 'Лекторий');


--
-- TOC entry 5054 (class 0 OID 18165)
-- Dependencies: 228
-- Data for Name: Rooms; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Rooms" VALUES (3, 1, 20, 350, 1, 0, 'Общая зона с комфортными креслами', 4.00, 'open-space-room.jpg', 'Open Space');
INSERT INTO public."Rooms" VALUES (4, 2, 12, 2000, 2, 15, 'Премиум-класс, кожаные кресла', 4.80, 'busines_room.jpg', 'Бизнес-зал');
INSERT INTO public."Rooms" VALUES (5, 3, 30, 3500, 3, 0, 'Для презентаций и вебинаров', 4.50, 'media-room.jpg', 'Медиа-студия');
INSERT INTO public."Rooms" VALUES (6, 4, 4, 800, 1, 5, 'Изолированный кабинет для переговоров', 4.10, 'cab5.jpg', 'Кабинет №5');
INSERT INTO public."Rooms" VALUES (16, 2, 1, 100, 1, 1, NULL, 0, 'c2a4161b-6735-4245-bc0e-d883d2ed0ad3.jpg', 'Orca');
INSERT INTO public."Rooms" VALUES (17, 4, 1, 100, 1, 1, NULL, 0, 'fc459183-654b-4161-a16a-cd36e329d9f0.jpg', 'jfy');
INSERT INTO public."Rooms" VALUES (18, 3, 1, 100, 1, 1, NULL, 0, '220ee0b4-1ff3-4258-9628-f15c12200578.jpg', 'hippo');
INSERT INTO public."Rooms" VALUES (2, 1, 8, 1500, 2, 10, 'Оформлена живыми растениями', 4.70, 'green-room.jpg', 'Зеленая комната');
INSERT INTO public."Rooms" VALUES (23, 2, 1, 100, 1, 25, NULL, 0, '1a21561c-3068-4ff1-ba11-8f83f7782c38.png', 'ваым');
INSERT INTO public."Rooms" VALUES (25, 4, 15, 1500, 2, 10, NULL, 0, '36535182-8d78-46f9-9b55-3c261a84069c.jpg', 'kivi');


--
-- TOC entry 5056 (class 0 OID 18179)
-- Dependencies: 230
-- Data for Name: Status; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Status" VALUES (1, 'Подтверждено');
INSERT INTO public."Status" VALUES (2, 'Новое');
INSERT INTO public."Status" VALUES (3, 'Отменено');
INSERT INTO public."Status" VALUES (4, 'Завершено');


--
-- TOC entry 5050 (class 0 OID 18142)
-- Dependencies: 224
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Users" VALUES (4, 'Морозова Ирина Алексеевна', 'i.morozova@cowork.ru', '79151112233', 'oper123', 2, false);
INSERT INTO public."Users" VALUES (5, 'Тимофеев Артем Денисович', 'artem.t@mail.ru', '79264567890', 'client321', 3, false);
INSERT INTO public."Users" VALUES (6, 'Крылова Светлана Игоревна', 'svetlana.k@yandex.ru', '79097654321', 'client321', 3, false);
INSERT INTO public."Users" VALUES (1, 'Воронов Андрей Михайлович', 'a.voronov@cowork.ru', '79161234567', 'admin2024', 1, false);
INSERT INTO public."Users" VALUES (2, 'Белова Екатерина Дмитриевна', 'e.belova@cowork.ru', '79269876543', 'admin2024', 1, false);
INSERT INTO public."Users" VALUES (3, 'Новиков Павел Сергеевич', 'p.novikov@cowork.ru', '79031234567', 'oper123', 2, false);


--
-- TOC entry 5068 (class 0 OID 0)
-- Dependencies: 219
-- Name: AdditionalServices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AdditionalServices_Id_seq"', 4, true);


--
-- TOC entry 5069 (class 0 OID 0)
-- Dependencies: 235
-- Name: Bookings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Bookings_Id_seq"', 9, true);


--
-- TOC entry 5070 (class 0 OID 0)
-- Dependencies: 231
-- Name: Equipment_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Equipment_Id_seq"', 9, true);


--
-- TOC entry 5071 (class 0 OID 0)
-- Dependencies: 221
-- Name: Role_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Role_Id_seq"', 3, true);


--
-- TOC entry 5072 (class 0 OID 0)
-- Dependencies: 225
-- Name: RoomType_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."RoomType_Id_seq"', 4, true);


--
-- TOC entry 5073 (class 0 OID 0)
-- Dependencies: 227
-- Name: Rooms_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Rooms_Id_seq"', 26, true);


--
-- TOC entry 5074 (class 0 OID 0)
-- Dependencies: 229
-- Name: Status_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Status_Id_seq"', 4, true);


--
-- TOC entry 5075 (class 0 OID 0)
-- Dependencies: 223
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 21, true);


--
-- TOC entry 4870 (class 2606 OID 18130)
-- Name: AdditionalServices _additionalservices__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AdditionalServices"
    ADD CONSTRAINT _additionalservices__pk PRIMARY KEY ("Id");


--
-- TOC entry 4888 (class 2606 OID 18219)
-- Name: Bookings _bookings__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT _bookings__pk PRIMARY KEY ("Id");


--
-- TOC entry 4882 (class 2606 OID 18203)
-- Name: Equipment _equipment__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Equipment"
    ADD CONSTRAINT _equipment__pk PRIMARY KEY ("Id");


--
-- TOC entry 4872 (class 2606 OID 18140)
-- Name: Role _role__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Role"
    ADD CONSTRAINT _role__pk PRIMARY KEY ("Id");


--
-- TOC entry 4878 (class 2606 OID 18177)
-- Name: Rooms _rooms__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT _rooms__pk PRIMARY KEY ("Id");


--
-- TOC entry 4876 (class 2606 OID 18163)
-- Name: RoomType _roomtype__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RoomType"
    ADD CONSTRAINT _roomtype__pk PRIMARY KEY ("Id");


--
-- TOC entry 4880 (class 2606 OID 18187)
-- Name: Status _status__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Status"
    ADD CONSTRAINT _status__pk PRIMARY KEY ("Id");


--
-- TOC entry 4874 (class 2606 OID 18153)
-- Name: Users _users__pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT _users__pk PRIMARY KEY ("Id");


--
-- TOC entry 4886 (class 2606 OID 18227)
-- Name: BookingAdditionalService bookingadditionalservice_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookingAdditionalService"
    ADD CONSTRAINT bookingadditionalservice_pk PRIMARY KEY ("BookingId", "AdditionalServiceId");


--
-- TOC entry 4884 (class 2606 OID 18223)
-- Name: RoomEquipment roomequipment_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RoomEquipment"
    ADD CONSTRAINT roomequipment_pk PRIMARY KEY ("RoomId", "EquipmentId");


--
-- TOC entry 4893 (class 2606 OID 18268)
-- Name: BookingAdditionalService bookingadditionalservice_additionalservices_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookingAdditionalService"
    ADD CONSTRAINT bookingadditionalservice_additionalservices_fk FOREIGN KEY ("AdditionalServiceId") REFERENCES public."AdditionalServices"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4894 (class 2606 OID 18263)
-- Name: BookingAdditionalService bookingadditionalservice_bookings_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BookingAdditionalService"
    ADD CONSTRAINT bookingadditionalservice_bookings_fk FOREIGN KEY ("BookingId") REFERENCES public."Bookings"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4895 (class 2606 OID 18238)
-- Name: Bookings bookings_rooms_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT bookings_rooms_fk FOREIGN KEY ("RoomId") REFERENCES public."Rooms"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4896 (class 2606 OID 18243)
-- Name: Bookings bookings_status_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT bookings_status_fk FOREIGN KEY ("StatusId") REFERENCES public."Status"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4897 (class 2606 OID 18233)
-- Name: Bookings bookings_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT bookings_users_fk FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4891 (class 2606 OID 18258)
-- Name: RoomEquipment roomequipment_equipment_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RoomEquipment"
    ADD CONSTRAINT roomequipment_equipment_fk FOREIGN KEY ("EquipmentId") REFERENCES public."Equipment"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4892 (class 2606 OID 18253)
-- Name: RoomEquipment roomequipment_rooms_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RoomEquipment"
    ADD CONSTRAINT roomequipment_rooms_fk FOREIGN KEY ("RoomId") REFERENCES public."Rooms"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4890 (class 2606 OID 18248)
-- Name: Rooms rooms_roomtype_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT rooms_roomtype_fk FOREIGN KEY ("RoomTypeId") REFERENCES public."RoomType"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4889 (class 2606 OID 18228)
-- Name: Users users_role_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_role_fk FOREIGN KEY ("RoleId") REFERENCES public."Role"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2026-06-04 09:20:22

--
-- PostgreSQL database dump complete
--

\unrestrict SG9ktwNtAFuDzqSmu86KSBfdMm84KhU5cGG18czCpb6U47MPZCFILCYxw1faOKE

